# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

# Credit: https://docs.github.com/en/code-security/dependabot/working-with-dependabot/dependabot-options-reference#required-keys
version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files
    directory: "/"
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: "daily"
  # Enable version updates for pip
  - package-ecosystem: "pip"
    # Look for `requirements.txt` files
    directory: "/src/vanguards/"
    schedule:
      interval: "daily"
  # Enable version updates for Docker
  - package-ecosystem: "docker"
    # Look for Dockerfiles
    directory: "/"
    schedule:
      interval: "daily"
